name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.8.3
  get_it: ^8.0.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  table_calendar: ^3.0.9
  intl: ^0.20.2
  fl_chart: ^0.68.0
  pdf: ^3.10.7
  path_provider: ^2.1.2 
  permission_handler: ^11.1.0
  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/